### ISSUE TITLE
Degree Day Calculation Error

### ISSUE THREAD

**Issue by SIBeckers** [ptitle/envirem#1]
Why does the degree day calculation not take into account the correct number of days for each month?

**Comment by ptitle** [comment]
I made a simplifying assumption by defining all months as having 30 days. I would be surprised if providing more specific numbers of days would make much of a difference,  but I am curious and will take a look, but probably won't have time until September.

**Comment by ptitle** [comment]
The function for growing degree days now incorporates the proper number of days per month.
