### ISSUE TITLE
Degree Days gives incorrect results 

### ISSUE THREAD

**Issue by see24** [ptitle/envirem#2]
I agree with issue #1 that it would be better to include the actual number of days in each month but I have a larger concern about `growingDegDays`. 

I created my own function to calculate growing degree days and then when I found the envirem package I wanted to compare it to my function. They returned very different results. After looking at the source code for both I was confident that `growingDegDays` contains an error. 
Here is the code for my function:
```
calc_DD5 <- function(Tave){
  DD5_1 <- Vectorize(function(Tave){
    if(is.na(Tave)){
      return(NA_real_)
    }
    if(Tave < 5){
      return(0)
    } else {
      (Tave) * 30
    }
  })
  
  mon_DD5 <- raster::calc(Tave, fun = function(x){DD5_1(x)})
  
  DD5 <- sum(mon_DD5) 
  DD5
}
```
And here is the source code for `growingDegDays` for comparison

```
growingDegDays <- function(meantempstack, baseTemp, tempScale = 1) {
  meantempstack <- meantempstack[[order(as.numeric(gsub("[a-zA-Z]+_([0-9]+)$", "\\1", names(meantempstack))))]]
  
  # we are operating in deg C, rather than deg C * tempScale
  meantempstack <- meantempstack / tempScale
  
  #get raster of number of months > baseTemp
  logicstack <- meantempstack > baseTemp
  logicsum <- sum(logicstack)
  
  #get rasterstack of temps above baseTemp (set all temps below baseTemp to 0)
  for (i in 1:raster::nlayers(meantempstack)) {
    cells <- which(raster::values(meantempstack[[i]]) < baseTemp)
    if (length(cells) > 0) {
      meantempstack[[i]][cells] <- 0
    }
  }
  
  #formula: summation of temps for all months with temp > baseTemp * total number of days in those months
  #sum temps
  meantempstack <- sum(meantempstack)
  res <- raster::overlay(meantempstack, logicsum, fun = function(a,b) {return(a * b * 30)})
  names(res) <- paste0('growingDegDays', baseTemp)
  return(res)
}
```
So I have done the multiplication first and then summed over all the months whereas `growingDegDays` takes the sum of temperatures for all months and then multiplies by the number of days in a month times the number of months. This sounds the same when written out with words but in fact they are not the same. This is easier to see if we look at the math

Take x to equal the number of days in a month, take a-l to be the mean temp in each month after setting to 0 any month with temp less than baseTemp 
So growing degree days equals:
GDD = ax + bx + cx ... + lx
If we factor out the x we would get 
GDD = x(a + b + c ... + l)

Therefore you don't need to multiply 30 times the number of months times the sum of mean temperatures. You just need to multiply sum of mean temp times 30. 

 So the third last line would be
```
res <- raster::overlay(meantempstack,  fun = function(a) {return(a  * 30)})
```
And you could get rid of the `logicsum` part.

**Comment by ptitle** [comment]
Thanks for this! I'll take a closer look soon.

**Comment by see24** [comment]
I have written a new version that is faster than the one I showed above and comparable to `growingDegDays`  if you set `memsafe = FALSE` 
```
calc_DDx <- function(Tave, baseTemp, memsafe = TRUE){
  if(memsafe){
    res <- raster::calc(Tave, function(x){
      Ndays <- c(31,28,31,30,31,30,31,31,30,31,30,31)
      ifelse(x < baseTemp, 0, (x - baseTemp)*Ndays)
    })
    res <- sum(res)
  } else {
    Ndays <- c(31,28,31,30,31,30,31,31,30,31,30,31)
    
    for (i in 1:raster::nlayers(Tave)) {
      Tave[[i]] <- ifelse(raster::values(Tave[[i]]) < baseTemp, 0,
                          (raster::values(Tave[[i]])- baseTemp)*Ndays[i])
    }
    res <- sum(Tave)
  }
  names(res) <- paste0("growingDegDays", baseTemp)
  return(res)
}
```
`calc` from the raster package will automatically process large rasters in chunks so that they won't be read into memory all at once. However, for smaller rasters the version that uses `calc` is significantly slower therefore I included the `memsafe` argument so you can decide which version to use. 

Another thing I discovered while looking into this was the function `clusterR` which allows a function that operates on a raster and the calculation for one cell is independent of other cells to be run in parallel.  In case it is useful to others it works like this:
```
beginCluster()
ndcalc_DD5_P <- clusterR(tave, calc_DDx,
                         args = list(baseTemp = 5))
endCluster()
```

**Comment by ptitle** [comment]
Thanks for bringing this to my attention. The current function is indeed incorrect. I've taken your recommendations and written a new version of the function that should be correct now. I'm closing this issue, but please let me know if you see any other issues. Thanks again!
