### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by EcoFang41** [ptitle/envirem#3]
Hi. Please help me.
Why when I using `generateRasters` or `layerCreation` function, I get a similar error message:

...splitting rasterstack...
Error in (function (classes, fdef, mtable)  :   unable to find an inherited method for function ‘raster’ for signature ‘"NULL"’

**Comment by ptitle** [comment]
Can you install the R package from github and try this again? I've made a number of changes over the last few days.
Do: `devtools::install_github('ptitle/envirem')`

**Comment by EcoFang41** [comment]
Thank you for the answer!  
Yes, I used this package from the CRAN repository.  I understood that the problem arises when generating not a complete set of variables.
Are there any significant changes in variables calculations in package from Github?  Just I generated variables used CRAN package.)

**Comment by ptitle** [comment]
No, nothing has changed in the formulae for the variables, just miscellaneous aspects of the R package, including bugs that led to the error you saw. But if you already generated rasters with the CRAN version, you should be fine.
