### ISSUE TITLE
Problem with nTiles in generateRasters

### ISSUE THREAD

**Issue by pedef** [ptitle/envirem#7]
Hi Pascal, 

I need your help to troubleshoot the below error message when calling generateRasters with the nTiles argument:
`generateRasters(var = 'annualPET',
                 prefix = 'byTiles_',
                 maindir = vars_path, 
                 outputDir = outdir, 
                 nTiles = 4)
	Splitting rasters into tiles...
	_tile1
Error in .local(x, ...) : no filenames supplied
In addition: There were 50 or more warnings (use warnings() to see the first 50)`

The error does not appear when omitting the nTiles argument. I use assignNames and verifyFileStructure and show no issue with the naming pattern. 

Any help is much appreciated!

**Comment by ptitle** [comment]
Hi,
I'm not sure if I found the problem (or resolved a separate new issue), but I made a few changes. Please install from github via `remotes::install_github('ptitle/envirem/envirem')` and try again, and let me know if that solved your issue. 

I do need to more broadly rewrite this package to remove dependencies on gdal and sp, and move to sf and terra, so this is all going to change in the near future regardless.

**Comment by pedef** [comment]
Thank you for your prompt response. I will go ahead and download the github version. Meanwhile I had tried to manually split rasters into tiles and the generateRaster function worked correctly. Looking forward to the update of the package with terra.

**Comment by ptitle** [comment]
The package is now updated. There is no longer the tiling option, since the terra package, which this package uses under the hood, has its own memory management for large rasters.

**Comment by gok-wolf** [comment]
Thanks, we will try it..
